# Generated by Django 2.1.4 on 2019-01-03 07:42

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank='True', upload_to='')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bg_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', '이미지형식')], max_length=20, verbose_name='포트폴리오 타입')),
                ('main_img', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('main_title', models.CharField(max_length=30, verbose_name='제목')),
                ('sub_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='부제목')),
                ('content', models.TextField(verbose_name='설명글')),
                ('used_info', models.CharField(choices=[('y', '사용'), ('n', '사용안함')], default='n', max_length=5, verbose_name='추가설명')),
                ('info_title1', models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO 타이틀1')),
                ('info_content1', models.TextField(blank=True, null=True, verbose_name='INFO 내용1')),
                ('info_title2', models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO 타이틀2')),
                ('info_content2', models.TextField(blank=True, null=True, verbose_name='INFO 내용2')),
                ('info_title3', models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO 타이틀3')),
                ('info_content3', models.TextField(blank=True, null=True, verbose_name='INFO 내용3')),
                ('info_url', models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO url')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='home.Portfolio')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='타이틀')),
                ('logo', models.CharField(max_length=30, verbose_name='메인화면로고')),
                ('one_row', models.CharField(max_length=80, verbose_name='1줄')),
                ('user_mail', models.CharField(max_length=60, verbose_name='이메일')),
                ('skin_type', models.CharField(choices=[('default.css', 'default'), ('amber.css', 'amber'), ('blue.css', 'blue'), ('blue-grey.css', 'blue-grey'), ('brown.css', 'brown'), ('cyan.css', 'cyan'), ('deep-orange.css', 'deep-orange'), ('deep-purple.css', 'deep-purple'), ('green.css', 'green'), ('indigo.css', 'indigo'), ('light-blue.css', 'light-blue'), ('light-green.css', 'light-green'), ('lime.css', 'lime'), ('orange.css', 'orange'), ('pink.css', 'pink'), ('purple.css', 'purple'), ('red.css', 'red'), ('teal.css', 'teal'), ('yellow.css', 'yellow')], default='default.css', max_length=20, verbose_name='스킨')),
                ('using_sns', models.BooleanField(default=True, verbose_name='SNS 사용여부')),
            ],
        ),
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns_type', models.CharField(choices=[('ti-facebook', 'FaceBook'), ('ti-github', 'Github'), ('ti-youtube', 'Youtube'), ('ti-instagram', 'Instagram'), ('ti-twitter-alt', 'Twitter')], max_length=30, verbose_name='SNS 종류')),
                ('sns_url', models.CharField(max_length=60, verbose_name='SNS Url')),
            ],
        ),
        migrations.AddField(
            model_name='bg_image',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_images', to='home.Setting'),
        ),
    ]
