# Generated by Django 2.1.4 on 2018-12-31 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Bg_Image',
        ),
    ]
