# Generated by Django 2.1.4 on 2018-12-31 06:40

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181231_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank='True', upload_to='')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='bg_image',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to=''),
        ),
    ]
