# Generated by Django 2.1.4 on 2018-12-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181231_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='photo_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='photo_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
