# Generated by Django 2.1.4 on 2018-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181231_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='about',
            name='photo_width',
        ),
        migrations.AddField(
            model_name='setting',
            name='skin_type',
            field=models.CharField(choices=[('default.css', 'default'), ('amber.css', 'amber'), ('blue.css', 'blue'), ('blue-grey.css', 'blue-grey'), ('brown.css', 'brown'), ('cyan.css', 'cyan'), ('deep-orange.css', 'deep-orange'), ('deep-purple.css', 'deep-purple'), ('green.css', 'green'), ('indigo.css', 'indigo'), ('light-blue.css', 'light-blue'), ('light-green.css', 'light-green'), ('lime.css', 'lime'), ('orange.css', 'orange'), ('pink.css', 'pink'), ('purple.css', 'purple'), ('red.css', 'red'), ('teal.css', 'teal'), ('yellow.css', 'yellow')], default='default.css', max_length=20, verbose_name='스킨'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.CharField(max_length=30, verbose_name='메인화면로고'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='one_row',
            field=models.CharField(max_length=80, verbose_name='1줄'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='title',
            field=models.CharField(max_length=30, verbose_name='타이틀'),
        ),
    ]
