# Generated by Django 2.1.4 on 2018-12-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181231_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sns_type', models.CharField(choices=[('ti-facebook', '페이스북'), ('ti-github', '깃허브'), ('ti-youtube', '유튜브'), ('ti-instagram', '인스타그램'), ('ti-twitter-alt', '트위터')], max_length=30, verbose_name='SNS 종류')),
            ],
        ),
        migrations.AddField(
            model_name='setting',
            name='using_sns',
            field=models.BooleanField(default=True, verbose_name='SNS 사용여부'),
        ),
    ]
