# Generated by Django 2.1.4 on 2019-01-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_sns_sns_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='user_mail',
            field=models.CharField(default='test@naver.com', max_length=60, verbose_name='이메일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sns',
            name='sns_type',
            field=models.CharField(choices=[('ti-facebook', 'FaceBook'), ('ti-github', 'Github'), ('ti-youtube', 'Youtube'), ('ti-instagram', 'Instagram'), ('ti-twitter-alt', 'Twitter')], max_length=30, verbose_name='SNS 종류'),
        ),
    ]
