# Generated by Django 2.1.4 on 2019-01-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_portfolio_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='sub_title',
            field=models.CharField(default='test', max_length=30, verbose_name='제목'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_title',
            field=models.CharField(max_length=30, verbose_name='제목'),
        ),
    ]
