# Generated by Django 2.1.4 on 2019-01-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190102_0448'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio_Image',
            new_name='PortfolioImage',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sub_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='부제목'),
        ),
    ]
