# Generated by Django 2.1.4 on 2019-01-02 06:38

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190102_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='home.Portfolio')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.RemoveField(
            model_name='portfolioimage',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='bg_image',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bg_images', to='home.Setting'),
        ),
        migrations.DeleteModel(
            name='PortfolioImage',
        ),
    ]
