# Generated by Django 2.1.4 on 2019-01-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190102_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='info_content1',
            field=models.TextField(blank=True, null=True, verbose_name='INFO 내용1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='info_content2',
            field=models.TextField(blank=True, null=True, verbose_name='INFO 내용2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='info_content3',
            field=models.TextField(blank=True, null=True, verbose_name='INFO 내용3'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='info_title1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO 타이틀1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='info_title2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO 타이틀2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='info_title3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO 타이틀3'),
        ),
    ]
