# Generated by Django 2.1.4 on 2019-01-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190102_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='info_url',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='INFO url'),
        ),
    ]
